/*

 BKG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 19
   Tile set      : D:\Programs\C\Pong\bkg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_mapWidth 21
#define bkg_mapHeight 19
#define bkg_mapBank 0

extern unsigned char bkg_map[];

/* End of BKG_MAP.H */
